# Default values for coraza-spoa.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ghcr.io/corazawaf/coraza-spoa
  pullPolicy: IfNotPresent
  # -- SemVer `X.X.X` or git `sha256:digest`
  tag: ""

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

volumes: []
  # - name: crs
  #   emptyDir: {}

volumeMounts: []
  # - name: crs
  #   mountPath: /etc/crs

initContainers: []
  # - name: crs
  #   image: busybox:1.36
  #   env:
  #     - name: CRS
  #       value: "4.17.1"
  #     - name: WP_CRS
  #       value: "1.1.0"
  #   command:
  #     - /bin/sh
  #   args:
  #     - "-c"
  #     - |
  #       ### Download CRS and WordPress CRS plugin to later use the following includes:
  #       # Include /etc/crs/plugins/wordpress-rule-exclusions-before.conf
  #       # Include /etc/crs/rules/*.conf
  #       wget -O /etc/crs/crs.tar.gz https://github.com/coreruleset/coreruleset/releases/download/v$(CRS)/coreruleset-$(CRS)-minimal.tar.gz \
  #       && tar --strip-components=1 -xzf /etc/crs/crs.tar.gz -C /etc/crs \
  #       && wget -O /etc/crs/wp-crs.tar.gz https://github.com/coreruleset/wordpress-rule-exclusions-plugin/archive/refs/tags/v$(WP_CRS).tar.gz \
  #       && tar --strip-components=2 -xzf /etc/crs/wp-crs.tar.gz wordpress-rule-exclusions-plugin-$(WP_CRS)/plugins -C /etc/crs/plugins \
  #       && rm -f /etc/crs/crs.tar.gz /etc/crs/wp-crs.tar.gz
  #   volumeMounts:
  #     - name: crs
  #       mountPath: /etc/crs

sidecarContainers: []

metrics:
  enabled: true
  port: 9100
  serviceMonitor:
    enabled: false

# -- Coraza SPOA configuration: https://github.com/corazawaf/coraza-spoa/blob/main/example/coraza-spoa.yaml
config:
  bind: 0.0.0.0:9000
  log_file: /dev/stdout
  log_format: json
  log_level: info
  default_application: default
  applications:
    - name: default
      log_file: /dev/stdout
      log_format: json
      log_level: error
      response_check: false
      transaction_ttl_ms: 60000
      directives: |
        Include @coraza.conf-recommended
        Include @crs-setup.conf.example
        Include /etc/coraza/before.conf
        Include @owasp_crs/*.conf
        Include /etc/coraza/after.conf
        SecRuleEngine On

# -- Custom rules that will be mounted as separate files.
rules:
  # -- These rules will be mounted at: `/etc/coraza/before.conf`
  before: |
    # Include this file before default CRS rules
  # -- These rules will be mounted at: `/etc/coraza/after.conf`
  after: |
    # Include this file after default CRS rules
  # -- These rules will be mounted at: `/etc/coraza/extra.conf`
  extra: |
    # Use this file for additional configuration flexibility
