apiVersion: v1
kind: Service
metadata:
  name: {{ include "coraza-caddy.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.namespaceOverride }}
  labels:
    {{- include "coraza-caddy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      protocol: TCP
      name: http
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "coraza-caddy.selectorLabels" . | nindent 4 }}
